[package]
name = "smartzip-cli"
version = "0.1.0-beta.1"
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[[bin]]
name = "smartzip"
path = "src/main.rs"

[dependencies]
libc.workspace = true
tokio-util.workspace = true
chrono = "0.4"
clap.workspace = true
serde_json.workspace = true
smartzip-archive.workspace = true
smartzip-core.workspace = true
smartzip-config.workspace = true
smartzip-db.workspace = true
smartzip-engine.workspace = true
smartzip-passwords.workspace = true
smartzip-scanner.workspace = true
tokio.workspace = true
smartzip-platform.workspace = true
async-trait.workspace = true
