[package]
name = "smartzip-scanner"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
aho-corasick.workspace = true
binwalk.workspace = true
crc32fast.workspace = true
serde.workspace = true
smartzip-core = { path = "../smartzip-core" }

[dev-dependencies]
zip.workspace = true
tempfile.workspace = true
